version: "2"
linters:
  enable:
    - ginkgolinter
  settings:
    ginkgolinter:
      forbid-focus-container: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: ST1019
      - path: (.+)\.go$
        text: SA1019
      - path: (.+)\.go$
        text: ST1005
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
