version: "2"
run:
  timeout: 10m
  go: "1.24"
  build-tags:
    - tools
    - e2e
  allow-parallel-runners: true
linters:
  enable:
    - errcheck
    - ginkgolinter
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    ginkgolinter:
      forbid-focus-container: true
  disable: []
