---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br-100
spec:
  capture:
    default-gw: routes.running.destination=="0.0.0.0/0"
    base-iface: interfaces.name==capture.default-gw.routes.running.0.next-hop-interface
  desiredState:
    interfaces:
        - name: "base.100"
          type: vlan
          state: up 
          vlan:
            base-iface: "{{ capture.base-iface.interfaces.0.name }}"
            id: 100
        - name: br-100
          type: linux-bridge
          state: up
          ipv4:
            enabled: false
          ipv6:
            enabled: false
          bridge:
            options:
              stp:
                enabled: false
            port:
            - name: base.100
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: proxy-arp
  name: proxy-arp
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
      - bridge: {}
        name: multus
        macAddress: 6a:f0:93:58:ec:3f
      rng: {}
    resources:
      requests:
        memory: 1024M
  networks:
  - multus:
      networkName: br-100
    name: multus 
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: quay.io/kubevirt/fedora-with-test-tooling-container-disk:devel
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
    name: cloudinitdisk
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: br-100
spec:
  config: >
    {
      "cniVersion": "0.4.0", 
      "name": "br-100-vmi",
      "plugins": [{
              "type": "bridge",
              "bridge": "br-100",
              "ipam": {}
      }]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: br-100-proxy-arp
spec:
  config: >
    {
      "cniVersion": "0.4.0", 
      "name": "br-100-pods",
      "plugins": [{
              "type": "bridge",
              "bridge": "br-100",
              "ipam": {}
      }, 
      {
        "type": "tuning",
        "sysctl": {
                "net.ipv4.conf.net1.proxy_arp": "1"
        }
      }]
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: proxy
  labels:
    name: proxy
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{"interface":"net1","name":"br-100-proxy-arp","namespace":"default"}]'
spec:
  containers:
  - image: alpine
    command:
      - /bin/sh
      - "-c"
      - "ip route replace 192.168.6.0/24 dev net1 && apk update && apk add iptables && iptables -t nat -A PREROUTING -p tcp -i eth0 -j DNAT --to-destination 192.168.6.2 && iptables -t nat -A POSTROUTING -s 192.168.6.2 -j MASQUERADE && sleep infinity"
    imagePullPolicy: IfNotPresent
    name: alpine
    securityContext:
      privileged: true
      capabilities:
        add: 
        - ALL
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: dnsmasq
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{"interface":"net1","name":"br-100","namespace":"default"}]'
spec:
  containers:
  - image: quay.io/coreos/dnsmasq
    command:
      - /bin/sh
      - "-c"
      - "ip a add 192.168.6.1/24 dev net1 && dnsmasq -d --interface=net1 --dhcp-option=option:classless-static-route,169.254.1.2/0 --dhcp-option=option:router,169.254.1.2 --dhcp-host=6a:f0:93:58:ec:3f,192.168.6.2 --dhcp-range=192.168.6.2,192.168.6.200,infinite"
    imagePullPolicy: IfNotPresent
    name: dnsmasq
    securityContext:
      privileged: true
      capabilities:
        add: 
        - ALL
  restartPolicy: Always



